
[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects pour SEO
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Page 404 personnalisée
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Configuration du site
[build.environment]
  SITE_NAME = "Plomberie Express Paris"
  BUSINESS_TYPE = "plombier"
