[build]
  publish = "out"
  functions = "netlify/functions"

[dev]
  port = 8888
  targetPort = 3000
  functionsPort = 9999

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"

# Variables d'environnement
[context.production.environment]
  CMS_PASSWORD = "admin123"

[context.deploy-preview.environment]
  CMS_PASSWORD = "admin123"